// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package translation.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class _TranslateTextAction extends CustomJavaAction<java.lang.String>
{
	private java.lang.String inputText;
	private java.lang.String inputLanguageCode;
	private java.lang.String outputLanguageCode;

	public _TranslateTextAction(IContext context, java.lang.String inputText, java.lang.String inputLanguageCode, java.lang.String outputLanguageCode)
	{
		super(context);
		this.inputText = inputText;
		this.inputLanguageCode = inputLanguageCode;
		this.outputLanguageCode = outputLanguageCode;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "_TranslateTextAction";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
