// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package textanalytics.actions;

import java.math.BigDecimal;
import java.util.ArrayList;
import com.mendix.cognitiveservices.contracts.textanalytics.Entity;
import com.mendix.cognitiveservices.contracts.textanalytics.EntityType;
import com.mendix.cognitiveservices.contracts.textanalytics.Request;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class _DetectEntitiesAction extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String text;
	private java.lang.String languageCode;

	public _DetectEntitiesAction(IContext context, java.lang.String text, java.lang.String languageCode)
	{
		super(context);
		this.text = text;
		this.languageCode = languageCode;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(!Utils.IsStringValid(text)) {
			return null;
		}
		
		var context = this.getContext();
		var service = ServiceLocator.INSTANCE.getInstance(this.getContext());
		if(!Utils.IsStringValid(languageCode)) {
			languageCode = Utils.getDefaultLangauge(context);
		}
		service.open();
		var req = new Request(text, languageCode);
		var result = service.detectEntities(req).get();
		service.close();
		var list = new ArrayList<IMendixObject>();
		for(var item : result) {
			list.add(getEntity(context, item));
		}
		return list;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "_DetectEntitiesAction";
	}

	// BEGIN EXTRA CODE
	private IMendixObject getEntity(IContext context, Entity item) throws CoreException {
		var result = new textanalytics.proxies.Entity(context);
		result.setEntityType(getEntityType(item.type));
		result.setText(item.text);
		result.setBeginOffset(item.beginOffset);
		result.setEndOffset(item.endOffset);
		result.setConfidenceScore(BigDecimal.valueOf(item.confidenceScore));
		result.commit(context);
		return result.getMendixObject();
	}
	
	private textanalytics.proxies.EntityType getEntityType(EntityType entityType) {
		switch(entityType) {
			case PERSON:
				return textanalytics.proxies.EntityType.Person;
			case LOCATION:
				return textanalytics.proxies.EntityType.Location;
			case ORGANIZATION:
				return textanalytics.proxies.EntityType.Organization;
			case COMMERCIAL_ITEM:
				return textanalytics.proxies.EntityType.Commercial_Item;
			case EVENT:
				return textanalytics.proxies.EntityType.Event;
			case DATE:
				return textanalytics.proxies.EntityType.Date;
			case QUANTITY:
				return textanalytics.proxies.EntityType.Quantity;
			case TITLE:
				return textanalytics.proxies.EntityType.Title;
			default:
				return textanalytics.proxies.EntityType.Other;
		}
		
	}
	// END EXTRA CODE
}
