// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package textanalytics.actions;

import java.math.BigDecimal;
import com.mendix.cognitiveservices.contracts.textanalytics.Request;
import com.mendix.cognitiveservices.contracts.textanalytics.Sentiment;
import com.mendix.cognitiveservices.contracts.textanalytics.SentimentType;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class _DetectSentimentAction extends CustomJavaAction<IMendixObject>
{
	private java.lang.String text;
	private java.lang.String languageCode;

	public _DetectSentimentAction(IContext context, java.lang.String text, java.lang.String languageCode)
	{
		super(context);
		this.text = text;
		this.languageCode = languageCode;
	}

	@java.lang.Override
	public IMendixObject executeAction() throws Exception
	{
		// BEGIN USER CODE
		if(!Utils.IsStringValid(text)) {
			return null;
		}
		
		var context = this.getContext();
		var service = ServiceLocator.INSTANCE.getInstance(this.getContext());
		if(!Utils.IsStringValid(languageCode)) {
			languageCode = Utils.getDefaultLangauge(context);
		}
		service.open();
		var req = new Request(text, languageCode);
		var result = service.detectSentiment(req).get();
		service.close();
		return getEntity(context, result);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "_DetectSentimentAction";
	}

	// BEGIN EXTRA CODE
	private IMendixObject getEntity(IContext context, Sentiment item) throws CoreException {
		var result = new textanalytics.proxies.Sentiment(context);
		var score = new textanalytics.proxies.SentimentScore(context);
		score.setPositive(BigDecimal.valueOf(item.score.positive));
		score.setNegative(BigDecimal.valueOf(item.score.negative));
		score.setNeutral(BigDecimal.valueOf(item.score.neutral));
		score.setMixed(BigDecimal.valueOf(item.score.mixed));
		result.setSentimentType(getEntityType(item.type));
		result.setSentiment_SentimentScore(context, score);
		result.commit(context);
		return result.getMendixObject();
	}
	
	private textanalytics.proxies.SentimentType getEntityType(SentimentType entityType) {
		switch(entityType) {
			case POSITIVE:
				return textanalytics.proxies.SentimentType.Positive;
			case NEGATIVE:
				return textanalytics.proxies.SentimentType.Negative;
			case MIXED:
				return textanalytics.proxies.SentimentType.Mixed;
			default:
				return textanalytics.proxies.SentimentType.Neutral;
		}
	}
	// END EXTRA CODE
}
