// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package main.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class _GetToken extends CustomJavaAction<java.lang.String>
{
	private java.lang.String provider;
	private java.lang.String service;

	public _GetToken(IContext context, java.lang.String provider, java.lang.String service)
	{
		super(context);
		this.provider = provider;
		this.service = service;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		var service = ServiceLocator.INSTANCE.getInstance(provider, this.getContext());
		var token = service.createCredentials(this.service).get();
		var result = token.toJson();
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "_GetToken";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
