// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.services.ProducerService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * This java action publishes a business event according to the published business event service document in which the entity passed as parameter here is configured.
 * 
 * Subject: Subject of the business event. Subject can be anything you consider useful, it’s like a short description of what can be expected in the payload, similar to email subject. It will help subscribed apps decide if the event might be useful to them.
 * 
 * Event Data: The entity that you want to publish. This should be an entity that you have configured to inherit from the `BusinessEvent`.
 * 
 * NOTE
 * This java action will commit all event objects at the start of the publishing process. In case something goes wrong during the publishing process a retry mechanism will be triggered for up to 48 hours. Once a retry is successful a second commit happens to the business event object to update the `EventId` and `PublishedTimestamp` attributes.
 */
public class PublishBusinessEvent_V2 extends CustomJavaAction<java.lang.Void>
{
	private com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate Subject;
	private IMendixObject __BusinessEvent;
	private businessevents.proxies.PublishedBusinessEvent BusinessEvent;

	public PublishBusinessEvent_V2(IContext context, com.mendix.systemwideinterfaces.javaactions.parameters.IStringTemplate Subject, IMendixObject BusinessEvent)
	{
		super(context);
		this.Subject = Subject;
		this.__BusinessEvent = BusinessEvent;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.BusinessEvent = this.__BusinessEvent == null ? null : businessevents.proxies.PublishedBusinessEvent.initialize(getContext(), __BusinessEvent);

		// BEGIN USER CODE
		Core.getLogger("BusinessEvents").error("This java action should be replaced build time by the extension and therefore never run");
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PublishBusinessEvent_V2";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
