// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package businessevents.actions;

import com.mendix.databroker.services.ProducerService;
import com.mendix.databroker.utils.ConfigurationProvider;
import com.mendix.databroker.utils.CoreProxyImpl;
import com.mendix.databroker.utils.exceptions.PublishFailedException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;

/**
 * Action responsible for publishing the entity to Kafka.
 */
public class PublishEvents extends CustomJavaAction<java.lang.Void>
{
	private IMendixObject __BusinessEvent;
	private businessevents.proxies.Outbox BusinessEvent;

	public PublishEvents(IContext context, IMendixObject BusinessEvent)
	{
		super(context);
		this.__BusinessEvent = BusinessEvent;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		this.BusinessEvent = this.__BusinessEvent == null ? null : businessevents.proxies.Outbox.initialize(getContext(), __BusinessEvent);

		// BEGIN USER CODE
		if (this.BusinessEvent != null) {
			ConfigurationProvider configurationProvider = new ConfigurationProvider(CoreProxyImpl.INSTANCE);
			ProducerService producerService = new ProducerService(configurationProvider, CoreProxyImpl.INSTANCE);
			producerService.sendEvent(this.__BusinessEvent);
		} else {
			throw new PublishFailedException("Empty object received for publishing event", null);
		}
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "PublishEvents";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
